name: CI API

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@4

    - name: Set up Node.js
      uses: actions/setup-node@3
      with:
        node-version: 22

    - name: Install dependencies
      run: cd api; npm ci

    - name: Build API
      run: cd api; npm run build
  
    - name: Run tests
      run: cd api; npm test
